class_name:          "config"
item_root:           "//ns2:nsiOrganizationData"
item:
  spz:               "ns2:code"
  full_name:         "*[name()='fullName']"
  name:              "*[name()='shortName']"
  inn:               "*[name()='inn']"
  kpp:               "*[name()='kpp']"
  legal:             "*[name()='legalAddress']"
  business:          "*[name()='postalAddress']"
  status:            "ns2:status"
  gmt:               "ns2:offset"
  website:           "ns2:website"
  phone:             "ns2:phone"
  fax:               "ns2:fax"
  email:             "ns2:email"
  contact_email:     "ns2:contactEmail"
  firm_type:         "ns2:fz223type/ns2:name"
  okato:             "ns2:okato"
  role:              "ns2:isCustomer"
  okved:             "*[local-name()='okved']/ns2:isMain[text()='true']/../ns2:code"
compound:
  contact:
    last_name:         "ns2:contactLastName"
    first_name:        "ns2:contactFirstName"
    middle_name:       "ns2:contactMiddleName"
