class_name:          "config"
item_root:           "//xmlns:nsiOrganization"
item:
  spz:               "oos:regNumber"
  role:              "oos:organizationRole"
  full_name:         "oos:fullName"
  name:              "oos:shortName"
  inn:               "oos:INN"
  kpp:               "oos:KPP"
  firm_type:         "oos:organizationType/oos:name"
  firm_type_id:      "oos:organizationType/oos:code"
  level_id:          "oos:subordinationType"
  belong_admin:      "oos:orderingAgency/oos:fullName"
  belong_admin_id:   "oos:orderingAgency/oos:regNum"
  top_level_firm:    "oos:headAgency/oos:fullName"
  top_level_firm_id: "oos:headAgency/oos:regNum"
  okopf:             "oos:OKOPF/oos:code"
  okpo:              "oos:OKPO"
  okved:             "oos:OKVED"
  ogrn:              "oos:OGRN"
  okato:             "oos:factualAddress/oos:OKATO"
  website:           "oos:url"
  gmt:               "oos:timeZone"
  phone:             "oos:phone"
  fax:               "oos:fax"
  email:             "oos:email"
  legal:             "oos:addressLine"
  business:          "oos:postalAddress"
  region:            "oos:factualAddress/oos:region/oos:fullName"
compound:
  contact:
    last_name:         "oos:contactPerson/oos:lastName"
    first_name:        "oos:contactPerson/oos:firstName"
    middle_name:        "oos:contactPerson/oos:middleName"
