class_name:          "config"
item_root:           "//vacancy"
item:
  name:              "company/name"
  phone:             "company/phone"
  email:             "company/email"
  business:          "location"
  contact:           "contact-name"
  industry:          "industry"
  is_agency:         "hr-agency"
